### ISSUE TITLE
[CI]: add semantic release

### ISSUE THREAD

**Issue by dubisdev** [cerebroapp/cerebro#584]
We can use semantic release GH action to analyze commits and automate releases and changelogs.

## Roadmap
I will update it with PRs.

- [ ] Get version from `app.getVersion()` and add it to `process.env.CEREBRO_VERSION`. By doing this, we dont depend on the `package.json` for getting the version and we can set it dinamically in CI with the result of the semantic-release.
  - [ ] Change `version` core plugin to get the version from `process.env.CEREBRO_VERSION`.
  - [ ] docs: update developers API so they know this new env variable is available. 
- [ ] Add linter to commits so we ensure they follow `conventional-commit` specification.
  - [ ] Add commitizen --> cli tool for writting conventional commits
  - [ ] Add `husky` and `commitlint` to lint commits by using git hooks.
- [ ] Add semantic-release step to GH actions
  - [ ] Move build step to new GH action, triggered by new releases.
    - Get the release version
    - Set it in CI by using the electron-builder cli options
    Should work with `electron-builder -c.extraMetadata.version={{ semantic-release output version }}`
    - Build the executables
